### ISSUE TITLE
JobException in ERROR Failed to start a transfer

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#554] opened 2024-04-23 09:46 UTC
## Description
- Job in error 

## Current behavior
- Job in error 

````
{
	"job": {
		"id": "f228d4f5-c3c7-434e-8ec7-4b6c0b5f8432",
		"globalAssetId": "urn:uuid:8724338c-5c85-4c34-91eb-e2735d58fb0d",
		"state": "ERROR",
		"exception": {
			"exception": "org.eclipse.tractusx.irs.connector.job.JobException",
			"errorDetail": "Failed to start a transfer",
			"exceptionDate": "2024-04-23T09:42:02.269209736Z"
		},
		"createdOn": "2024-04-23T09:35:55.543464314Z",
		"startedOn": "2024-04-23T09:35:55.543581713Z",
		"lastModifiedOn": "2024-04-23T09:42:02.269206036Z",
		"completedOn": "2024-04-23T09:42:02.269204837Z",
````

## Expected behavior
- IRS Job returns JobReponse without ERROR 

## Steps to reproduce the Bug
- DEV Environment 
- globalAssetID  urn:uuid:8724338c-5c85-4c34-91eb-e2735d58fb0d
- BPN BPNL00000003AVTH
- asBuilt

**Comment by dsmf** [comment] 2024-04-30 16:35
@mkanal : 
- Cannot find the Job with this ID? Which ENV?
- Which aspects? collectAspects? lookupBPNs? depth?

**Comment by mkanal** [comment] 2024-04-30 18:35
@dsmf 
Env is DEV: 
Note: There was a reset since then so job might not be present any more.

There are multiple Jobs in ERROR state please get in contact with Jaro. 

````
Given I register an IRS job for globalAssetId "urn:uuid:8724338c-5c85-4c34-91eb-e2735d58fb0d" and BPN "BPNL00000003AVTH"
And collectAspects "true"
And depth 10
And direction "downward"
And bomLifecycle "asBuilt"
And lookupBPNs "false"
And aspects :
  | urn:samm:io.catenax.batch:3.0.0#Batch |
When I get the job-id
````

**Comment by dsmf** [comment] 2024-05-02 11:47
Not reproducible on DEV with the above parameters:
```
{
	"job": {
		"id": "5510dc66-0edc-44af-b867-33bb507c76c8",
		"globalAssetId": "urn:uuid:8724338c-5c85-4c34-91eb-e2735d58fb0d",
		"state": "COMPLETED",
		"exception": null,
		"createdOn": "2024-05-02T10:49:32.909494162Z",
		"startedOn": "2024-05-02T10:49:32.909575763Z",
		"lastModifiedOn": "2024-05-02T10:59:56.474404223Z",
		"completedOn": "2024-05-02T10:59:56.474405223Z",
		"summary": {
			"asyncFetchedItems": {
				"running": 0,
				"completed": 175,
				"failed": 0
			},
			"bpnLookups": {
				"completed": 0,
				"failed": 0
			}
		},
		"parameter": {
			"bomLifecycle": "asBuilt",
			"aspects": [
				"urn:samm:io.catenax.batch:3.0.0#Batch"
			],
			"depth": 10,
			"bpn": "BPNL00000003AVTH",
			"direction": "downward",
			"collectAspects": true,
			"lookupBPNs": false,
			"auditContractNegotiation": true,
			"callbackUrl": null
		}
	},
...
```

**Comment by dsmf** [comment] 2024-05-06 08:20
another trial with `"lookupBPNs": true,`
job id 2fc94e5c-95f6-4b41-9d42-0bba45e5f984
=>
```
{
	"job": {
		"id": "2fc94e5c-95f6-4b41-9d42-0bba45e5f984",
		"globalAssetId": "urn:uuid:8724338c-5c85-4c34-91eb-e2735d58fb0d",
		"state": "RUNNING",
		"exception": null,
		"createdOn": "2024-05-02T16:31:44.714228824Z",
		"startedOn": "2024-05-02T16:31:44.714352826Z",
		"lastModifiedOn": "2024-05-02T16:31:44.728810932Z",
		"completedOn": null,
		"summary": {
			"asyncFetchedItems": {
				"running": 1,
				"completed": 0,
				"failed": 0
			},
			"bpnLookups": {
				"completed": 0,
				"failed": 0
			}
		},
		"parameter": {
			"bomLifecycle": "asBuilt",
			"aspects": [
				"urn:samm:io.catenax.batch:3.0.0#Batch"
			],
			"depth": 10,
			"bpn": "BPNL00000003AVTH",
			"direction": "downward",
			"collectAspects": true,
			"lookupBPNs": true,
			"auditContractNegotiation": true,
			"callbackUrl": null
		}
	},
	"relationships": [],
	"shells": [],
	"tombstones": [],
	"submodels": [],
	"bpns": []
}
```
Here the job seems to stay in state RUNNING forever. But this is another issue which should be resolved by #568

**Comment by dsmf** [comment] 2024-05-06 08:25
Hi @ds-jhartmann, could you also check if you can reproduce this please? If you cannot reproduce it either we can close the bug, I guess.

**Comment by dsmf** [comment] 2024-05-06 16:39
```
{
	"job": {
		"id": "db05b66d-c6f5-45a9-957c-b1f37e52ba7c",
		"globalAssetId": "urn:uuid:8724338c-5c85-4c34-91eb-e2735d58fb0d",
		"state": "ERROR",
		"exception": {
			"exception": "org.eclipse.tractusx.irs.connector.job.JobException",
			"errorDetail": "Failed to start a transfer",
			"exceptionDate": "2024-05-02T16:16:46.580252951Z"
		},
		"createdOn": "2024-05-02T16:07:58.34393778Z",
		"startedOn": "2024-05-02T16:07:58.344037282Z",
		"lastModifiedOn": "2024-05-02T16:16:46.58024925Z",
		"completedOn": "2024-05-02T16:16:46.58024825Z",
		"summary": {
			"asyncFetchedItems": {
				"running": 51,
				"completed": 73,
				"failed": 0
			},
			"bpnLookups": {
				"completed": 0,
				"failed": 0
			}
		},
		"parameter": {
			"bomLifecycle": "asBuilt",
			"aspects": [
				"urn:samm:io.catenax.serial_part:3.0.0#SerialPart",
				"urn:samm:io.catenax.single_level_bom_as_built:3.0.0#SingleLevelBomAsBuilt",
				"urn:samm:io.catenax.just_in_sequence_part:3.0.0#JustInSequencePart",
				"urn:samm:io.catenax.batch:3.0.0#Batch"
			],
			"depth": 100,
			"bpn": "BPNL00000003AVTH",
			"direction": "downward",
			"collectAspects": true,
			"lookupBPNs": false,
			"auditContractNegotiation": false,
			"callbackUrl": null
		}
	},
...
```

**Comment by dsmf** [comment] 2024-05-06 16:54
Hi @ds-jhartmann, can you review please? Does not seem reproducible / probably fixed by some other story / bugfix.

**Comment by mkanal** [comment] 2024-05-07 14:33
Tested is not reproducible on DEV in the current setup. Ready for review.

**Comment by mkanal** [comment] 2024-05-08 10:16
PO acceptance in representation of @jzbmw . 
According to multiple code changes, this is not reproducible anymore. If this issues remains, the bug will be reopened.

**Closed** 2024-05-08 10:16 UTC
Labels: bug
