### ISSUE TITLE
[EDC] Implement functionality to cache and re-use EDR Tokens

### ISSUE THREAD

**Issue by jzbmw** [eclipse-tractusx/item-relationship-service#256] opened 2023-11-03 12:46 UTC
As user,
I want that the EDR-token is cached and reused for subsequent request of assets with the same EDC contract offer,
so that we get advantages from performance

## Hints / Details

- Implement the functionality according to the concept [EDR-Token-Cache-and-reuse.md](https://github.com/catenax-ng/tx-item-relationship-service/blob/a2f149cc081483d2ed864b9de7dc5299e6b3f744/docs/concept/EDR-Token-Cache-and-reuse.md)  
- Take a look at the registry client implementation [here](https://github.com/catenax-ng/tx-item-relationship-service/blob/main/irs-registry-client/src/main/java/org/eclipse/tractusx/irs/registryclient/decentral/DecentralDigitalTwinRegistryService.java#L98). We already do EDR caching here.
- Pull into irs-edc-client if possible to reduce duplication
- REQUESTOR: Trace-X Performance enhancements

### Outcome
- ...
### Acceptance Criteria
- [ ] EDR Token caching has been implemented
- [ ] implementation is done according to concept
- [ ] tests have been updated
- [ ] documentation in Arc42 has been updated

## Out of Scope

- ...

**Comment by jzbmw** [comment] 2023-12-19 09:07
Seemed to be a bigger effort than expected. 
Size might be a L than a M

**Comment by ds-alexander-bulgakov** [comment] 2024-01-10 10:22
*QA-Update*: Some issues could be found during testing in the last days which could be detected by tombstone "Index 1 out of bounds for length 1" in processstep "SubmodelRequest". The reason for this could be identified and fixed in branch "edc-exception-test", retest ongoing.

**Comment by ds-alexander-bulgakov** [comment] 2024-01-11 14:26
No more issues could be found during last QA-review on DEV and ESS-INT, previous fixes were successful. All three token states could be reproduced and proven with logs:
Log for new token:
"Staring new contract negotiation."

Log for existing and valid token:
"Endpoint data reference found in cache with token status valid, reusing cache record."

Log for expired token:
"Cached endpoint data reference has expired token. Refreshing token without new contract negotiation for contractAgreementId: YzY3**..."

The arch42 has been updated as well. Ticket is ready for PO-review, FYI @jzbmw.

**Closed** 2024-01-12 09:03 UTC
Labels: dependencies
