### ISSUE TITLE
Register policy definition for certain BPNLs

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#199] opened 2023-10-20 09:58 UTC
## User Story

*As* Business App
*I want* to register policies in the policy store for given BPNLs
*so that* I am able to define a concrete policy for each company individual  

##Links 
- relates to https://github.com/eclipse-tractusx/item-relationship-service/issues/505

## Hints / Details / NFR (Technical, Design & Content) : 
* it shall be possible to add multiple policies for the same asset for different BPNL`s. For example Emea and China suppliers, or other regulatory requirements
* eclipse-tractusx/sig-release#453

## Acceptance Criteria
* [ ] Refactor allowed BPN's
* [ ] Policy Store API allows registering policy for one or more BPNLs 
* [ ] Policy Store API allows adding BPNLs and removing BPNLs 
* [ ] PolicyChecker checks policies registered for the BPNL of the data offer 
* [ ] In case there is no BPNL related to a policy, the policy is used for any negotiations (data consumption) and any notification (data provisioning)  
* [ ] EDC Usage Policy Validation is extended and executed only for policies related to the BPN of the asset to be negotiated (this counts for  asset consumption and notifications  process )

### API POST /irs/policies 
Post a list of policies for a given BPNL. 

Request body 
````
"validUntil": "2024-01-31T11:55:07.718Z",
"businessPartnerNumber": "BPNLXXXXXXXX", 
"policies" : [ {policy: {}]
````

Response 
````
   policyId
````

### API GET /irs/policies 
Provide policies for given businessPartnerNumbers or all if no businessPartnerNumbers  is set 

|Parameter| Type| Default | Description |
|--|---|---|---|
| businessPartnerNumbers | array | empty | List of policies for bpns

 Response body 
````
[ 
    { 
     "businessPartnerNumber" : ["BPNL....","BPNL...."]
      "policies" : [{policyId},{policyId}]
   }
]
````

## PUT /irs/policy/{policyId}

Updates an exisiting policy with new values 

### Parameter 
- policyId

### RequestBody 
````
"validUntil": "2024-01-31T11:55:07.718Z",
"businessPartnerNumber": ["BPNLXXXXXXXX", ]
"policies" : [ {policyId},{policyId}]
````

##  DELETE 
- no change policyId is the id to identify policy instead of BPN

# Clarification 
*

**Comment by ds-jhartmann** [comment] 2024-02-20 13:17
Planning 2:
- Add field `businessPartnerNumber` to policy API
- Adjust policy validation to check for the BPN
- businessPartnerNumber is optional, if not set, the policy applies to all BPNs

**Comment by ds-psosnowski** [comment] 2024-02-22 11:55
confirmed with @jjeroch - policy creation can be extended to add a list of policies instead of one policy per request. That means if we have multiple bpns and multiple policies we should register all policies for all bpns passed in a request.

**Comment by ds-psosnowski** [comment] 2024-03-05 15:46
PR: https://github.com/catenax-ng/tx-item-relationship-service/pull/802

**Comment by mkanal** [comment] 2024-03-22 14:42
@ds-jhartmann @ds-psosnowski is insomnia Collection up to date?

**Comment by dsmf** [comment] 2024-03-22 16:27
Hi @mkanal , according to the [commits](https://github.com/catenax-ng/tx-item-relationship-service/pull/802/commits) the Insomnia collection should be up to date, see [the following commit](https://github.com/catenax-ng/tx-item-relationship-service/pull/802/commits/2d4e1cb5e6e18e244c20a351b78637057f2afc97)

**Comment by mkanal** [comment] 2024-03-25 09:29
@dsmf 

# TestEnvironment DEV Insomnia Collection 

## Test Case 1 : Empty parameter 

### Steps 2 reproduce 

Call endpoint with empty parameter : {{IRS_HOST}}/irs/policies?bpnls=  :  no result 


## Test Case 2 : No valid BPNL 

#### Current behavior 
policy is returned for BPNL which does not exist 

#### Expected behavior 
No policy is returned as no policy exists for BPNL "1"

{{IRS_HOST}}/irs/policies?bpnls=1:  


````
{
	"1": [
		{
			"validUntil": "2029-03-25T09:10:59.128573961Z",
			"payload": {
				"@context": {
					"odrl": "http://www.w3.org/ns/odrl/2/"
				},
````

## Test Case 3 : BPNL BPNL00000001CRH1
{{IRS_HOST}}/irs/policies?bpnls=BPNL00000001CRH1

**Comment by mkanal** [comment] 2024-03-25 09:39
@dsmf 
Kindly ask to have a look if database has to be purged or why this default policy is added to any bpnls.

**Comment by dsmf** [comment] 2024-03-26 15:56
https://github.com/eclipse-tractusx/item-relationship-service/issues/249

**Comment by dsmf** [comment] 2024-03-28 03:53
PR https://github.com/catenax-ng/tx-item-relationship-service/pull/839 (still draft)

**Comment by dsmf** [comment] 2024-04-08 12:39
If a policy is not assigned to a BPN, should it then (A) apply to all BPNs or (B) only if no explicit policy is assigned to a BPN?
(at the moment A is implemented)

Answer  from @mkanal: Exactly (B)

**Comment by dsmf** [comment] 2024-04-09 15:17
### Pull Request https://github.com/catenax-ng/tx-item-relationship-service/pull/839

**Comment by dsmf** [comment] 2024-04-10 09:01
merged

**Comment by dsmf** [comment] 2024-04-10 09:23
ready for test

**Comment by dsmf** [comment] 2024-04-10 09:35
### Outcome:

acceptance criteria:
- [x] Allowed BPN's refactored
- [x] Policy Store API allows registering policy for one or more BPNLs
- [x] Policy Store API allows adding BPNLs and removing BPNLs (from policy, BPNL will remain in DB without policies)
- [x] PolicyChecker checks policies registered for the BPNL of the data offer
- [x] In case there is no BPNL related to a policy, the policy is used for any negotiations (data consumption) and any notification (data provisioning)
- [x] EDC Usage Policy Validation is extended and executed only for policies related to the BPN of the asset to be negotiated (this counts for asset consumption and notifications process )

additionally:
- [x] harmonized with https://github.com/eclipse-tractusx/item-relationship-service/issues/249 
- [x] changed API according to alignments because the definition in the story was inconsistent / wrong (see Insomnia collections), this includes consistent naming for business partner number parameters
- [x] business logic was moved from controller to service (separation of concerns: test of business logic in service only, controller test only web layer stuff)
- [x] should already contain implementation for
https://github.com/eclipse-tractusx/item-relationship-service/issues/505 (because we needed some validation anyway to avoid consequential errors)
- [x] irs-api.yaml updated
- [x] default handling clarified and corrected

**Comment by dsmf** [comment] 2024-04-10 10:47
Hi @mkanal, 

kindly ask you for clarification concerning https://github.com/catenax-ng/tx-item-relationship-service/commit/9ef45a6e09386e3e8d57e1d40b052bea04875e1c (see specific question in ms teams). 

If anything needs to be changed here, this would be out of scope of the current story. If this is the case create an new PBI for this please.

**Comment by ds-jhartmann** [comment] 2024-04-10 14:04
- Tested Policy creation for different BPNLs ✅
- Tested IRS Policy validation with accepted and unknown policies ✅

**Comment by ds-jhartmann** [comment] 2024-04-12 06:56
@jzbmw ready for PO acceptance

**Closed** 2024-04-15 12:24 UTC
Labels: hardening, policy_store, spill_over
